// eficompareutil.hpp was generated by ProtoGen version 3.1.d

#ifndef _EFICOMPAREUTIL_HPP
#define _EFICOMPAREUTIL_HPP

// Language target is C++

/*!
 * \file
 */

#include "eficomms.py.hpp"
#include <string>

#endif // _EFICOMPAREUTIL_HPP
