// efiprintutil.hpp was generated by ProtoGen version 3.1.d

#ifndef _EFIPRINTUTIL_HPP
#define _EFIPRINTUTIL_HPP

// Language target is C++

/*!
 * \file
 */

#include "eficomms.py.hpp"
#include <string>

#endif // _EFIPRINTUTIL_HPP
