// eficommsProtocol.c was generated by ProtoGen version 3.1.d

#include "eficommsProtocol.h"
#include "floatspecial.h"
#include "fielddecode.h"
#include "fieldencode.h"
#include "scaleddecode.h"
#include "scaledencode.h"

/*!
 * \brief Lookup label for 'efiPacketIds' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string label of the given entry
 */
const char* efiPacketIds_EnumLabel(int value)
{
    switch (value)
    {
    default:
        return "";
    case EFI_PKT_CANTRANSPORT:
        return translateeficomms("EFI_PKT_CANTRANSPORT");
    case EFI_PKT_PUMPCONFIGURATION:
        return translateeficomms("EFI_PKT_PUMPCONFIGURATION");
    case EFI_PKT_COMMCONFIGURATION:
        return translateeficomms("EFI_PKT_COMMCONFIGURATION");
    case EFI_PKT_SENSORCONFIGURATION:
        return translateeficomms("EFI_PKT_SENSORCONFIGURATION");
    case EFI_PKT_THROTTLECONFIGURATION:
        return translateeficomms("EFI_PKT_THROTTLECONFIGURATION");
    case EFI_PKT_RESERVED:
        return translateeficomms("EFI_PKT_RESERVED");
    case EFI_PKT_INJECTORCONFIGURATION:
        return translateeficomms("EFI_PKT_INJECTORCONFIGURATION");
    case EFI_PKT_RPMCONTROLLER:
        return translateeficomms("EFI_PKT_RPMCONTROLLER");
    case EFI_PKT_ENGINEWEAR:
        return translateeficomms("EFI_PKT_ENGINEWEAR");
    case EFI_PKT_TABLE:
        return translateeficomms("EFI_PKT_TABLE");
    case EFI_PKT_TABLEVALUE:
        return translateeficomms("EFI_PKT_TABLEVALUE");
    case EFI_PKT_RESERVED1:
        return translateeficomms("EFI_PKT_RESERVED1");
    case EFI_PKT_SOFTWAREINFO:
        return translateeficomms("EFI_PKT_SOFTWAREINFO");
    case EFI_PKT_STICKY_ERRORS:
        return translateeficomms("EFI_PKT_STICKY_ERRORS");
    case EFI_PKT_ENABLE:
        return translateeficomms("EFI_PKT_ENABLE");
    case EFI_PKT_USERTHROTTLE:
        return translateeficomms("EFI_PKT_USERTHROTTLE");
    case EFI_PKT_RPMCOMMAND:
        return translateeficomms("EFI_PKT_RPMCOMMAND");
    case EFI_PKT_REQUEST:
        return translateeficomms("EFI_PKT_REQUEST");
    case EFI_PKT_TELEMETRYTIME:
        return translateeficomms("EFI_PKT_TELEMETRYTIME");
    case EFI_PKT_TELEMETRYFAST:
        return translateeficomms("EFI_PKT_TELEMETRYFAST");
    case EFI_PKT_TELEMETRYSENSORS:
        return translateeficomms("EFI_PKT_TELEMETRYSENSORS");
    case EFI_PKT_TELEMETRYSENSORS2:
        return translateeficomms("EFI_PKT_TELEMETRYSENSORS2");
    case EFI_PKT_TELEMETRYFUEL:
        return translateeficomms("EFI_PKT_TELEMETRYFUEL");
    case EFI_PKT_TELEMETRYSLOW:
        return translateeficomms("EFI_PKT_TELEMETRYSLOW");
    case EFI_PKT_TELEMETRYCPU:
        return translateeficomms("EFI_PKT_TELEMETRYCPU");
    case EFI_PKT_TELEMETRYINJECTOR:
        return translateeficomms("EFI_PKT_TELEMETRYINJECTOR");
    case EFI_PKT_TELEMETRYERRORS:
        return translateeficomms("EFI_PKT_TELEMETRYERRORS");
    case EFI_PKT_NACK:
        return translateeficomms("EFI_PKT_NACK");
    case EFI_PKT_UNLOCK:
        return translateeficomms("EFI_PKT_UNLOCK");
    case EFI_PKT_LOCKCONTROL:
        return translateeficomms("EFI_PKT_LOCKCONTROL");
    case EFI_PKT_RESET:
        return translateeficomms("EFI_PKT_RESET");
    case EFI_PKT_FILE:
        return translateeficomms("EFI_PKT_FILE");
    case EFI_PKT_COMMENT:
        return translateeficomms("EFI_PKT_COMMENT");
    case EFI_PKT_STORAGE:
        return translateeficomms("EFI_PKT_STORAGE");
    case EFI_PKT_HARDWAREINFO:
        return translateeficomms("EFI_PKT_HARDWAREINFO");
    case EFI_PKT_TELEMETRYFASTSUM:
        return translateeficomms("EFI_PKT_TELEMETRYFASTSUM");
    case EFI_PKT_TELEMETRYSLOWSUM:
        return translateeficomms("EFI_PKT_TELEMETRYSLOWSUM");
    case EFI_PKT_BOOTLOADER:
        return translateeficomms("EFI_PKT_BOOTLOADER");
    case EFI_PKT_TELEMETRYSENSORS3:
        return translateeficomms("EFI_PKT_TELEMETRYSENSORS3");
    case EFI_PKT_CONFIGHASH:
        return translateeficomms("EFI_PKT_CONFIGHASH");
    case EFI_PKT_TELEMETRYCOMMS:
        return translateeficomms("EFI_PKT_TELEMETRYCOMMS");
    case EFI_PKT_OSCILLOSCOPE_SETUP:
        return translateeficomms("EFI_PKT_OSCILLOSCOPE_SETUP");
    case EFI_PKT_OSCILLOSCOPE_DATA:
        return translateeficomms("EFI_PKT_OSCILLOSCOPE_DATA");
    case EFI_PKT_DEBUG:
        return translateeficomms("EFI_PKT_DEBUG");
    case EFI_PKT_TESTMODE:
        return translateeficomms("EFI_PKT_TESTMODE");
    case EFI_PKT_TELEMETRYSDCARD:
        return translateeficomms("EFI_PKT_TELEMETRYSDCARD");
    case EFI_PKT_FUELUSED:
        return translateeficomms("EFI_PKT_FUELUSED");
    case EFI_PKT_TELEMETRYAUTOFUEL:
        return translateeficomms("EFI_PKT_TELEMETRYAUTOFUEL");
    case EFI_PKT_TELEMETRYSENSORS4:
        return translateeficomms("EFI_PKT_TELEMETRYSENSORS4");
    case EFI_PKT_ENGINEWEAREXT:
        return translateeficomms("EFI_PKT_ENGINEWEAREXT");
    case EFI_PKT_MAINTENANCECONFIGURATION:
        return translateeficomms("EFI_PKT_MAINTENANCECONFIGURATION");
    case EFI_PKT_MAINTENANCESTATUS:
        return translateeficomms("EFI_PKT_MAINTENANCESTATUS");
    case EFI_PKT_LOGENTRY:
        return translateeficomms("EFI_PKT_LOGENTRY");
    case EFI_PKT_CRANKSENSETIMING:
        return translateeficomms("EFI_PKT_CRANKSENSETIMING");
    case EFI_PKT_SDCARDJOURNAL:
        return translateeficomms("EFI_PKT_SDCARDJOURNAL");
    case EFI_PKT_INTERRUPTDETAILS:
        return translateeficomms("EFI_PKT_INTERRUPTDETAILS");
    case EFI_PKT_COOLINGCONFIGURATION:
        return translateeficomms("EFI_PKT_COOLINGCONFIGURATION");
    case EFI_PKT_NEWENGINECONFIGURATION:
        return translateeficomms("EFI_PKT_NEWENGINECONFIGURATION");
    case EFI_PKT_TELEMETRYGCU:
        return translateeficomms("EFI_PKT_TELEMETRYGCU");
    case EFI_PKT_TELEMETRYEXTENDEDOUTPUTS:
        return translateeficomms("EFI_PKT_TELEMETRYEXTENDEDOUTPUTS");
    case EFI_PKT_TELEMETRYOILINJ:
        return translateeficomms("EFI_PKT_TELEMETRYOILINJ");
    }
}

/*!
 * \brief Lookup title for 'efiPacketIds' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string title of the given entry (comment if no title given)
 */
const char* efiPacketIds_EnumTitle(int value)
{
    switch (value)
    {
    default:
        return "";
    case EFI_PKT_CANTRANSPORT:
        return translateeficomms("CAN transport");
    case EFI_PKT_PUMPCONFIGURATION:
        return translateeficomms("Fuel pump");
    case EFI_PKT_COMMCONFIGURATION:
        return translateeficomms("Communications");
    case EFI_PKT_SENSORCONFIGURATION:
        return translateeficomms("Sensor");
    case EFI_PKT_THROTTLECONFIGURATION:
        return translateeficomms("Throttle");
    case EFI_PKT_RESERVED:
        return translateeficomms("EFI_PKT_RESERVED");
    case EFI_PKT_INJECTORCONFIGURATION:
        return translateeficomms("Injector");
    case EFI_PKT_RPMCONTROLLER:
        return translateeficomms("RPM controller");
    case EFI_PKT_ENGINEWEAR:
        return translateeficomms("Engine wear");
    case EFI_PKT_TABLE:
        return translateeficomms("Table data");
    case EFI_PKT_TABLEVALUE:
        return translateeficomms("Table data value");
    case EFI_PKT_RESERVED1:
        return translateeficomms("EFI_PKT_RESERVED1");
    case EFI_PKT_SOFTWAREINFO:
        return translateeficomms("Software version");
    case EFI_PKT_STICKY_ERRORS:
        return translateeficomms("Sticky error telemetry");
    case EFI_PKT_ENABLE:
        return translateeficomms("Enable/disable command");
    case EFI_PKT_USERTHROTTLE:
        return translateeficomms("Throttle command");
    case EFI_PKT_RPMCOMMAND:
        return translateeficomms("RPM command");
    case EFI_PKT_REQUEST:
        return translateeficomms("Packet request command");
    case EFI_PKT_TELEMETRYTIME:
        return translateeficomms("Time telemetry");
    case EFI_PKT_TELEMETRYFAST:
        return translateeficomms("Fast telemetry");
    case EFI_PKT_TELEMETRYSENSORS:
        return translateeficomms("Sensors telemetry");
    case EFI_PKT_TELEMETRYSENSORS2:
        return translateeficomms("Sensors2 telemetry");
    case EFI_PKT_TELEMETRYFUEL:
        return translateeficomms("Fuel consumption telemetry");
    case EFI_PKT_TELEMETRYSLOW:
        return translateeficomms("Slow telemetry");
    case EFI_PKT_TELEMETRYCPU:
        return translateeficomms("CPU telemetry");
    case EFI_PKT_TELEMETRYINJECTOR:
        return translateeficomms("Injector telemetry");
    case EFI_PKT_TELEMETRYERRORS:
        return translateeficomms("Dynamic error telemetry");
    case EFI_PKT_NACK:
        return translateeficomms("Not-acknowledge report");
    case EFI_PKT_UNLOCK:
        return translateeficomms("Unlock command");
    case EFI_PKT_LOCKCONTROL:
        return translateeficomms("Locking");
    case EFI_PKT_RESET:
        return translateeficomms("Reset report");
    case EFI_PKT_FILE:
        return translateeficomms("File name");
    case EFI_PKT_COMMENT:
        return translateeficomms("Comment");
    case EFI_PKT_STORAGE:
        return translateeficomms("Storage command");
    case EFI_PKT_HARDWAREINFO:
        return translateeficomms("Hardware version");
    case EFI_PKT_TELEMETRYFASTSUM:
        return translateeficomms("Fast telemetry summary");
    case EFI_PKT_TELEMETRYSLOWSUM:
        return translateeficomms("Slow telemetry summary");
    case EFI_PKT_BOOTLOADER:
        return translateeficomms("Bootloader command and report");
    case EFI_PKT_TELEMETRYSENSORS3:
        return translateeficomms("Sensors3 telemetry");
    case EFI_PKT_CONFIGHASH:
        return translateeficomms("Validation");
    case EFI_PKT_TELEMETRYCOMMS:
        return translateeficomms("Telemetry about communications");
    case EFI_PKT_OSCILLOSCOPE_SETUP:
        return translateeficomms("Oscilloscope setup packet");
    case EFI_PKT_OSCILLOSCOPE_DATA:
        return translateeficomms("Oscilloscope data packet");
    case EFI_PKT_DEBUG:
        return translateeficomms("IntelliJect debug packet");
    case EFI_PKT_TESTMODE:
        return translateeficomms("IntelliJect test mode packet");
    case EFI_PKT_TELEMETRYSDCARD:
        return translateeficomms("Telemetry about the SD card");
    case EFI_PKT_FUELUSED:
        return translateeficomms("Fuel used");
    case EFI_PKT_TELEMETRYAUTOFUEL:
        return translateeficomms("Automatic fuel determination");
    case EFI_PKT_TELEMETRYSENSORS4:
        return translateeficomms("Sensors4 telemetry");
    case EFI_PKT_ENGINEWEAREXT:
        return translateeficomms("Extended engine wear");
    case EFI_PKT_MAINTENANCECONFIGURATION:
        return translateeficomms("Maintenance schedule");
    case EFI_PKT_MAINTENANCESTATUS:
        return translateeficomms("Maintenance status");
    case EFI_PKT_LOGENTRY:
        return translateeficomms("Engine logbook");
    case EFI_PKT_CRANKSENSETIMING:
        return translateeficomms("Crank wheel timing");
    case EFI_PKT_SDCARDJOURNAL:
        return translateeficomms("SD card journal information");
    case EFI_PKT_INTERRUPTDETAILS:
        return translateeficomms("Interrupt details");
    case EFI_PKT_COOLINGCONFIGURATION:
        return translateeficomms("Cooling");
    case EFI_PKT_NEWENGINECONFIGURATION:
        return translateeficomms("Engine");
    case EFI_PKT_TELEMETRYGCU:
        return translateeficomms("GCU Telemetry");
    case EFI_PKT_TELEMETRYEXTENDEDOUTPUTS:
        return translateeficomms("Extended outputs telemetry");
    case EFI_PKT_TELEMETRYOILINJ:
        return translateeficomms("Oil Injection Telemetry");
    }
}


/*!
 * \brief Lookup title for 'MaintenanceTriggers' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string title of the given entry (comment if no title given)
 */
const char* MaintenanceTriggers_EnumTitle(int value)
{
    switch (value)
    {
    default:
        return "";
    case maintenanceTriggerTime:
        return translateeficomms("Run time");
    case maintenanceTriggerRevs:
        return translateeficomms("Revolutions");
    case maintenanceTriggerHotTime:
        return translateeficomms("Hot time");
    case maintenanceTriggerHighLoadTime:
        return translateeficomms("Load time");
    case maintenanceTriggerStarts:
        return translateeficomms("Starts");
    case maintenanceTriggerCHT:
        return translateeficomms("CHT");
    case numMaintenanceTriggers:
        return translateeficomms("numMaintenanceTriggers");
    }
}

/*!
 * \brief Lookup comment for 'MaintenanceTriggers' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string comment of the given entry (title if no comment given)
 */
const char* MaintenanceTriggers_EnumComment(int value)
{
    switch (value)
    {
    default:
        return "";
    case maintenanceTriggerTime:
        return translateeficomms("Maintenance is triggered by engine run time");
    case maintenanceTriggerRevs:
        return translateeficomms("Maintenance is triggered by number of revolutions");
    case maintenanceTriggerHotTime:
        return translateeficomms("Maintenance is triggered by engine time above CHT limit");
    case maintenanceTriggerHighLoadTime:
        return translateeficomms("Maintenance is triggered by engine time above the high load threshold");
    case maintenanceTriggerStarts:
        return translateeficomms("Maintenance is triggered by number of engine starts");
    case maintenanceTriggerCHT:
        return translateeficomms("Maintenance is triggered by cylinder head temperature");
    case numMaintenanceTriggers:
        return translateeficomms("numMaintenanceTriggers");
    }
}


/*!
 * \brief Lookup title for 'efiTableList' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string title of the given entry (comment if no title given)
 */
const char* efiTableList_EnumTitle(int value)
{
    switch (value)
    {
    default:
        return "";
    case EFI_TABLE_FUEL:
        return translateeficomms("Fuel (μg/cc/rev)");
    case EFI_TABLE_SPARK1ADV:
        return translateeficomms("Spark Advance (°)");
    case EFI_TABLE_SPARK2DELAY:
        return translateeficomms("Spark2 Delay (°)");
    case EFI_TABLE_CHARGETEMP:
        return translateeficomms("Charge Temp coefficient");
    case EFI_TABLE_FM1:
        return translateeficomms("Fuel multiplier 1");
    case EFI_TABLE_INJECTOR1PHASE:
        return translateeficomms("Injector1 Phase (°)");
    case EFI_TABLE_INJECTOR1TRIM:
        return translateeficomms("Injector1 Trim (μs)");
    case EFI_TABLE_MINTHROTTLE:
        return translateeficomms("Min Throttle (%)");
    case EFI_TABLE_MAXTHROTTLE:
        return translateeficomms("Max Throttle (%)");
    case EFI_TABLE_SA1:
        return translateeficomms("Spark adder 1 (°)");
    case EFI_TABLE_FM2:
        return translateeficomms("Fuel multiplier 2");
    case EFI_TABLE_FM3:
        return translateeficomms("Fuel multiplier 3");
    case EFI_TABLE_MAP:
        return translateeficomms("MAP Estimate");
    case EFI_TABLE_SHAFTPOWER:
        return translateeficomms("Shaft Power (W)");
    case EFI_TABLE_INJECTOR2RATIO:
        return translateeficomms("Injector2 Ratio (%)");
    case EFI_TABLE_INJECTOR2PHASE:
        return translateeficomms("Injector2 Phase (°)");
    case EFI_TABLE_INJECTOR2TRIM:
        return translateeficomms("Injector2 Trim (μs)");
    case EFI_TABLE_FM4:
        return translateeficomms("Fuel multiplier 4");
    case EFI_TABLE_IGNDWELL:
        return translateeficomms("Ign Dwell (μs)");
    case EFI_TABLE_SA2:
        return translateeficomms("Spark adder 2 (°)");
    case EFI_TABLE_FM5:
        return translateeficomms("Fuel multiplier 5");
    case EFI_TABLE_INJECTOR3RATIO:
        return translateeficomms("Injector3 Ratio (%)");
    case EFI_TABLE_INJECTOR3PHASE:
        return translateeficomms("Injector3 Phase (°)");
    case EFI_TABLE_INJECTOR3TRIM:
        return translateeficomms("Injector3 Trim (μs)");
    case EFI_TABLE_SPARK3DELAY:
        return translateeficomms("Spark3 Delay (°)");
    case EFI_TABLE_MINTHROTTLE2:
        return translateeficomms("Min Throttle2 (%)");
    case EFI_TABLE_MAXTHROTTLE2:
        return translateeficomms("Max Throttle2 (%)");
    case EFI_TABLE_FM6:
        return translateeficomms("Fuel multiplier 6");
    case EFI_TABLE_FM7:
        return translateeficomms("Fuel multiplier 7");
    case EFI_TABLE_OILINJ_RATIO:
        return translateeficomms("Fuel to oil ratio");
    case EFI_TABLE_OILINJ_DUTY:
        return translateeficomms("Oil pump duty cycle (%)");
    case EFI_TABLE_OILINJ_OUTPUT:
        return translateeficomms("Oil pump output (μg/cycle)");
    case EFI_TABLE_SA3:
        return translateeficomms("Spark adder 3 (°)");
    case EFI_TABLE_USER1:
        return translateeficomms("User 1");
    case EFI_TABLE_USER2:
        return translateeficomms("User 2");
    case EFI_TABLE_USER3:
        return translateeficomms("User 3");
    case EFI_TABLE_USER4:
        return translateeficomms("User 4");
    }
}

/*!
 * \brief Lookup comment for 'efiTableList' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string comment of the given entry (title if no comment given)
 */
const char* efiTableList_EnumComment(int value)
{
    switch (value)
    {
    default:
        return "";
    case EFI_TABLE_FUEL:
        return translateeficomms("Fuel as micro-grams per revolution per cc of displacement.");
    case EFI_TABLE_SPARK1ADV:
        return translateeficomms("Spark1 advance in degrees.");
    case EFI_TABLE_SPARK2DELAY:
        return translateeficomms("Delay of spark2 after spark1 in degrees.");
    case EFI_TABLE_CHARGETEMP:
        return translateeficomms("Fraction of CHT (versus MAT) to use in the determination of the charge temperature.");
    case EFI_TABLE_FM1:
        return translateeficomms("First fuel multiplier.");
    case EFI_TABLE_INJECTOR1PHASE:
        return translateeficomms("First injector angle in degrees.");
    case EFI_TABLE_INJECTOR1TRIM:
        return translateeficomms("First injector start time in microseconds.");
    case EFI_TABLE_MINTHROTTLE:
        return translateeficomms("First minimum throttle in percent.");
    case EFI_TABLE_MAXTHROTTLE:
        return translateeficomms("First maximum throttle in percent.");
    case EFI_TABLE_SA1:
        return translateeficomms("First spark adder in degrees.");
    case EFI_TABLE_FM2:
        return translateeficomms("Second fuel multiplier.");
    case EFI_TABLE_FM3:
        return translateeficomms("Third fuel multiplier.");
    case EFI_TABLE_MAP:
        return translateeficomms("Ratio of manifold to baro pressure (for failed map sensor).");
    case EFI_TABLE_SHAFTPOWER:
        return translateeficomms("Shaft power in Watts on standard day.");
    case EFI_TABLE_INJECTOR2RATIO:
        return translateeficomms("Percentage of injector 2 versus injectors 1 and 3 in providing the total fuel flow.");
    case EFI_TABLE_INJECTOR2PHASE:
        return translateeficomms("Second injector angle in degrees.");
    case EFI_TABLE_INJECTOR2TRIM:
        return translateeficomms("Second injector start time in microseconds.");
    case EFI_TABLE_FM4:
        return translateeficomms("Fourth fuel multiplier.");
    case EFI_TABLE_IGNDWELL:
        return translateeficomms("Microseconds of time the ignition output is inactive between sparks.");
    case EFI_TABLE_SA2:
        return translateeficomms("Second spark adder in degrees.");
    case EFI_TABLE_FM5:
        return translateeficomms("Fifth fuel multiplier.");
    case EFI_TABLE_INJECTOR3RATIO:
        return translateeficomms("Percentage of injector 3 versus injectors 1 and 2 in providing the total fuel flow.");
    case EFI_TABLE_INJECTOR3PHASE:
        return translateeficomms("Third injector angle in degrees.");
    case EFI_TABLE_INJECTOR3TRIM:
        return translateeficomms("Third injector start time in microseconds.");
    case EFI_TABLE_SPARK3DELAY:
        return translateeficomms("Delay of spark3 after spark1 in degrees.");
    case EFI_TABLE_MINTHROTTLE2:
        return translateeficomms("Second minimum throttle in percent.");
    case EFI_TABLE_MAXTHROTTLE2:
        return translateeficomms("Second maximum throttle in percent.");
    case EFI_TABLE_FM6:
        return translateeficomms("Sixth fuel multiplier.");
    case EFI_TABLE_FM7:
        return translateeficomms("Seventh fuel multiplier.");
    case EFI_TABLE_OILINJ_RATIO:
        return translateeficomms("Desired ratio of fuel to oil.");
    case EFI_TABLE_OILINJ_DUTY:
        return translateeficomms("Percentage duty cycle of the oil injection pump.");
    case EFI_TABLE_OILINJ_OUTPUT:
        return translateeficomms("Output of the oil injection pump per pulse in micro-grams of oil.");
    case EFI_TABLE_SA3:
        return translateeficomms("Third spark adder in degrees.");
    case EFI_TABLE_USER1:
        return translateeficomms("First user table.");
    case EFI_TABLE_USER2:
        return translateeficomms("Second user table.");
    case EFI_TABLE_USER3:
        return translateeficomms("Third user table.");
    case EFI_TABLE_USER4:
        return translateeficomms("Fourth user table.");
    }
}


/*!
 * \brief Lookup title for 'efiTableIndex' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string title of the given entry (comment if no title given)
 */
const char* efiTableIndex_EnumTitle(int value)
{
    switch (value)
    {
    default:
        return "";
    case EFI_TBLIDX_NULL:
        return translateeficomms("1.0");
    case EFI_TBLIDX_THROTTLE:
        return translateeficomms("Throttle (%)");
    case EFI_TBLIDX_LOAD:
        return translateeficomms("Load (%)");
    case EFI_TBLIDX_RPM:
        return translateeficomms("RPM");
    case EFI_TBLIDX_BARO_RATIO:
        return translateeficomms("Baro ratio");
    case EFI_TBLIDX_MAP_RATIO:
        return translateeficomms("MAP ratio");
    case EFI_TBLIDX_CHARGE_TEMP_RATIO:
        return translateeficomms("Charge temp ratio");
    case EFI_TBLIDX_MAT_RATIO:
        return translateeficomms("MAT ratio");
    case EFI_TBLIDX_DENSITY_RATIO:
        return translateeficomms("Density ratio");
    case EFI_TBLIDX_ONEMINUS_DENSITY_RATIO:
        return translateeficomms("1 - Density ratio");
    case EFI_TBLIDX_MAT:
        return translateeficomms("MAT (C)");
    case EFI_TBLIDX_CHARGE_TEMP:
        return translateeficomms("Charge temp (C)");
    case EFI_TBLIDX_CHT:
        return translateeficomms("CHT (C)");
    case EFI_TBLIDX_CHTCOLD:
        return translateeficomms("CHT Cold (C)");
    case EFI_TBLIDX_CHTHOT:
        return translateeficomms("CHT Hot (C)");
    case EFI_TBLIDX_MAP:
        return translateeficomms("MAP (kPa)");
    case EFI_TBLIDX_BARO:
        return translateeficomms("Baro (kPa)");
    case EFI_TBLIDX_FUELP:
        return translateeficomms("Fuel pressure (kPa)");
    case EFI_TBLIDX_FUELP_RAW:
        return translateeficomms("Raw fuel press. (kPa)");
    case EFI_TBLIDX_VOLTAGE:
        return translateeficomms("Voltage (V)");
    case EFI_TBLIDX_REVS:
        return translateeficomms("Revolutions");
    case EFI_TBLIDX_TIME:
        return translateeficomms("Time (s)");
    case EFI_TBLIDX_THROTTLE_RATE:
        return translateeficomms("Throttle rate (%/s)");
    case EFI_TBLIDX_POS_THROTTLE_RATE:
        return translateeficomms("Pos throt. rate (%/s)");
    case EFI_TBLIDX_NEG_THROTTLE_RATE:
        return translateeficomms("Neg throt. rate (%/s)");
    case EFI_TBLIDX_RPM_RATE:
        return translateeficomms("RPM rate (rpm/s)");
    case EFI_TBLIDX_POS_RPM_RATE:
        return translateeficomms("Pos RPM rate (rpm/s)");
    case EFI_TBLIDX_NEG_RPM_RATE:
        return translateeficomms("Neg RPM rate (rpm/s)");
    case EFI_TBLIDX_OIL_TEMP:
        return translateeficomms("Oil temperature (C)");
    case EFI_TBLIDX_OIL_DUTY:
        return translateeficomms("Oil duty cycle (%)");
    case EFI_TBLIDX_OIL_ON_TIME:
        return translateeficomms("Oil on time (ms)");
    case EFI_TBLIDX_USER1:
        return translateeficomms("User 1");
    case EFI_TBLIDX_USER2:
        return translateeficomms("User 2");
    case EFI_TBLIDX_USER3:
        return translateeficomms("User 3");
    case EFI_TBLIDX_USER4:
        return translateeficomms("User 4");
    }
}

/*!
 * \brief Lookup comment for 'efiTableIndex' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string comment of the given entry (title if no comment given)
 */
const char* efiTableIndex_EnumComment(int value)
{
    switch (value)
    {
    default:
        return "";
    case EFI_TBLIDX_NULL:
        return translateeficomms("The value of 1.0.");
    case EFI_TBLIDX_THROTTLE:
        return translateeficomms("Position of the throttle in percent.");
    case EFI_TBLIDX_LOAD:
        return translateeficomms("Percent ratio of manifold pressure to barometric pressure.");
    case EFI_TBLIDX_RPM:
        return translateeficomms("Engine speed in revolutions per minute.");
    case EFI_TBLIDX_BARO_RATIO:
        return translateeficomms("Ratio of barometric air pressure to standard day pressure.");
    case EFI_TBLIDX_MAP_RATIO:
        return translateeficomms("Ratio of manifold air pressure to standard day pressure.");
    case EFI_TBLIDX_CHARGE_TEMP_RATIO:
        return translateeficomms("Ratio of absolute charge temperature to absolute charge temperature reference.");
    case EFI_TBLIDX_MAT_RATIO:
        return translateeficomms("Ratio of manifold air absolute temperature to standard day absolute temperature.");
    case EFI_TBLIDX_DENSITY_RATIO:
        return translateeficomms("Ratio of air density to standard day density.");
    case EFI_TBLIDX_ONEMINUS_DENSITY_RATIO:
        return translateeficomms("1.0 - the ratio of air density to standard day density.");
    case EFI_TBLIDX_MAT:
        return translateeficomms("Average manifold air temperature.");
    case EFI_TBLIDX_CHARGE_TEMP:
        return translateeficomms("Charge temperature.");
    case EFI_TBLIDX_CHT:
        return translateeficomms("Average cylinder head temperature.");
    case EFI_TBLIDX_CHTCOLD:
        return translateeficomms("Coldest cylinder head temperature.");
    case EFI_TBLIDX_CHTHOT:
        return translateeficomms("Hottest cylinder head temperature.");
    case EFI_TBLIDX_MAP:
        return translateeficomms("Manifold air pressure.");
    case EFI_TBLIDX_BARO:
        return translateeficomms("Barometric air pressure.");
    case EFI_TBLIDX_FUELP:
        return translateeficomms("Augmented fuel pressure (fuelp + baro - map).");
    case EFI_TBLIDX_FUELP_RAW:
        return translateeficomms("Gauge fuel pressure.");
    case EFI_TBLIDX_VOLTAGE:
        return translateeficomms("Voltage of the injector rail.");
    case EFI_TBLIDX_REVS:
        return translateeficomms("Engine revolutions since start.");
    case EFI_TBLIDX_TIME:
        return translateeficomms("Elapsed time since engine start.");
    case EFI_TBLIDX_THROTTLE_RATE:
        return translateeficomms("Rate of change of the throttle position.");
    case EFI_TBLIDX_POS_THROTTLE_RATE:
        return translateeficomms("Rate of change of the throttle position, if the throttle rate is positive, else zero.");
    case EFI_TBLIDX_NEG_THROTTLE_RATE:
        return translateeficomms("Rate of change of the throttle position, if the throttle rate is negative, else zero.");
    case EFI_TBLIDX_RPM_RATE:
        return translateeficomms("Rate of change of the engine speed.");
    case EFI_TBLIDX_POS_RPM_RATE:
        return translateeficomms("Rate of change of the engine speed, if the rpm rate is positive, else zero.");
    case EFI_TBLIDX_NEG_RPM_RATE:
        return translateeficomms("Rate of change of the engine speed, if the rpm rate is negative, else zero.");
    case EFI_TBLIDX_OIL_TEMP:
        return translateeficomms("Oil temperature.");
    case EFI_TBLIDX_OIL_DUTY:
        return translateeficomms("Duty cycle of the oil injection pump.");
    case EFI_TBLIDX_OIL_ON_TIME:
        return translateeficomms("The amount of time the oil injection pump is on per cycle.");
    case EFI_TBLIDX_USER1:
        return translateeficomms("Output of the user 1 table");
    case EFI_TBLIDX_USER2:
        return translateeficomms("Output of the user 2 table");
    case EFI_TBLIDX_USER3:
        return translateeficomms("Output of the user 3 table");
    case EFI_TBLIDX_USER4:
        return translateeficomms("Output of the user 4 table");
    }
}


/*!
 * \brief Lookup title for 'efiSDStatus' enum entry
 * 
 * \param value is the integer value of the enum entry
 * \return string title of the given entry (comment if no title given)
 */
const char* efiSDStatus_EnumTitle(int value)
{
    switch (value)
    {
    default:
        return "";
    case EFI_SD_HARDWARE_BAD:
        return translateeficomms("SD bad card");
    case EFI_SD_MBR_BAD:
        return translateeficomms("SD bad boot");
    case EFI_SD_VOLUME_BAD:
        return translateeficomms("SD bad volume");
    case EFI_SD_ROOT_BAD:
        return translateeficomms("SD bad root");
    case EFI_SD_FORMATTING:
        return translateeficomms("SD formatting");
    case EFI_SD_SETTINGUP:
        return translateeficomms("SD setting up");
    case EFI_SD_READY:
        return translateeficomms("SD ready");
    case EFI_SD_TRANSFER:
        return translateeficomms("SD transferring");
    }
}

// end of eficommsProtocol.c
