// efiprintutil.hpp was generated by ProtoGen version 3.1.d

#ifndef _EFIPRINTUTIL_HPP
#define _EFIPRINTUTIL_HPP

// Language target is C++

/*!
 * \file
 */

#include "eficomms.h"
#include <string>

//! Generate a string that describes the contents of a efiDate_t
std::string textPrintefiDate_t(const std::string& prename, const efiDate_t* user);

//! Read the contents of a efiDate_t from text
int textReadefiDate_t(const std::string& prename, const std::string& source, efiDate_t* user);

//! Generate a string that describes the contents of a efiDateTime_t
std::string textPrintefiDateTime_t(const std::string& prename, const efiDateTime_t* user);

//! Read the contents of a efiDateTime_t from text
int textReadefiDateTime_t(const std::string& prename, const std::string& source, efiDateTime_t* user);

//! Generate a string that describes the contents of a efiCrankSense_t
std::string textPrintefiCrankSense_t(const std::string& prename, const efiCrankSense_t* user);

//! Read the contents of a efiCrankSense_t from text
int textReadefiCrankSense_t(const std::string& prename, const std::string& source, efiCrankSense_t* user);

//! Generate a string that describes the contents of a efiTable1D_t
std::string textPrintefiTable1D_t(const std::string& prename, const efiTable1D_t* user);

//! Read the contents of a efiTable1D_t from text
int textReadefiTable1D_t(const std::string& prename, const std::string& source, efiTable1D_t* user);

//! Generate a string that describes the contents of a EngineWear packet
std::string textPrintefiEngineWearPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiEngineWear_t
std::string textPrintefiEngineWear_t(const std::string& prename, const efiEngineWear_t* user);

//! Read the contents of a efiEngineWear_t from text
int textReadefiEngineWear_t(const std::string& prename, const std::string& source, efiEngineWear_t* user);

//! Generate a string that describes the contents of a efiMaintenanceItemStatus_t
std::string textPrintefiMaintenanceItemStatus_t(const std::string& prename, const efiMaintenanceItemStatus_t* user);

//! Read the contents of a efiMaintenanceItemStatus_t from text
int textReadefiMaintenanceItemStatus_t(const std::string& prename, const std::string& source, efiMaintenanceItemStatus_t* user);

//! Generate a string that describes the contents of a MaintenanceStatus packet
std::string textPrintefiMaintenanceStatusPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiMaintenanceStatus_t
std::string textPrintefiMaintenanceStatus_t(const std::string& prename, const efiMaintenanceStatus_t* user);

//! Read the contents of a efiMaintenanceStatus_t from text
int textReadefiMaintenanceStatus_t(const std::string& prename, const std::string& source, efiMaintenanceStatus_t* user);

//! Generate a string that describes the contents of a LogEntry packet
std::string textPrintefiLogEntryPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiLogEntry_t
std::string textPrintefiLogEntry_t(const std::string& prename, const efiLogEntry_t* user);

//! Read the contents of a efiLogEntry_t from text
int textReadefiLogEntry_t(const std::string& prename, const std::string& source, efiLogEntry_t* user);

//! Generate a string that describes the contents of a File packet
std::string textPrintefiFilePkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiFile_t
std::string textPrintefiFile_t(const std::string& prename, const efiFile_t* user);

//! Read the contents of a efiFile_t from text
int textReadefiFile_t(const std::string& prename, const std::string& source, efiFile_t* user);

//! Generate a string that describes the contents of a Comment packet
std::string textPrintefiCommentPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiComment_t
std::string textPrintefiComment_t(const std::string& prename, const efiComment_t* user);

//! Read the contents of a efiComment_t from text
int textReadefiComment_t(const std::string& prename, const std::string& source, efiComment_t* user);

//! Generate a string that describes the contents of a LockControl packet
std::string textPrintefiLockControlPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiLockControl_t
std::string textPrintefiLockControl_t(const std::string& prename, const efiLockControl_t* user);

//! Read the contents of a efiLockControl_t from text
int textReadefiLockControl_t(const std::string& prename, const std::string& source, efiLockControl_t* user);

//! Generate a string that describes the contents of a ConfigHash packet
std::string textPrintefiConfigHashPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiConfigHash_t
std::string textPrintefiConfigHash_t(const std::string& prename, const efiConfigHash_t* user);

//! Read the contents of a efiConfigHash_t from text
int textReadefiConfigHash_t(const std::string& prename, const std::string& source, efiConfigHash_t* user);

//! Generate a string that describes the contents of a PumpConfiguration packet
std::string textPrintefiPumpConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiPumpConfiguration_t
std::string textPrintefiPumpConfiguration_t(const std::string& prename, const efiPumpConfiguration_t* user);

//! Read the contents of a efiPumpConfiguration_t from text
int textReadefiPumpConfiguration_t(const std::string& prename, const std::string& source, efiPumpConfiguration_t* user);

//! Generate a string that describes the contents of a efiCANconfig_t
std::string textPrintefiCANconfig_t(const std::string& prename, const efiCANconfig_t* user);

//! Read the contents of a efiCANconfig_t from text
int textReadefiCANconfig_t(const std::string& prename, const std::string& source, efiCANconfig_t* user);

//! Generate a string that describes the contents of a CommConfiguration packet
std::string textPrintefiCommConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiCommConfiguration_t
std::string textPrintefiCommConfiguration_t(const std::string& prename, const efiCommConfiguration_t* user);

//! Read the contents of a efiCommConfiguration_t from text
int textReadefiCommConfiguration_t(const std::string& prename, const std::string& source, efiCommConfiguration_t* user);

//! Generate a string that describes the contents of a SensorConfiguration packet
std::string textPrintefiSensorConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiSensorConfiguration_t
std::string textPrintefiSensorConfiguration_t(const std::string& prename, const efiSensorConfiguration_t* user);

//! Read the contents of a efiSensorConfiguration_t from text
int textReadefiSensorConfiguration_t(const std::string& prename, const std::string& source, efiSensorConfiguration_t* user);

//! Generate a string that describes the contents of a ThrottleConfiguration packet
std::string textPrintefiThrottleConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiThrottleConfiguration_t
std::string textPrintefiThrottleConfiguration_t(const std::string& prename, const efiThrottleConfiguration_t* user);

//! Read the contents of a efiThrottleConfiguration_t from text
int textReadefiThrottleConfiguration_t(const std::string& prename, const std::string& source, efiThrottleConfiguration_t* user);

//! Generate a string that describes the contents of a CoolingConfiguration packet
std::string textPrintefiCoolingConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiCoolingConfiguration_t
std::string textPrintefiCoolingConfiguration_t(const std::string& prename, const efiCoolingConfiguration_t* user);

//! Read the contents of a efiCoolingConfiguration_t from text
int textReadefiCoolingConfiguration_t(const std::string& prename, const std::string& source, efiCoolingConfiguration_t* user);

//! Generate a string that describes the contents of a EngineConfiguration packet
std::string textPrintefiEngineConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiEngineConfiguration_t
std::string textPrintefiEngineConfiguration_t(const std::string& prename, const efiEngineConfiguration_t* user);

//! Read the contents of a efiEngineConfiguration_t from text
int textReadefiEngineConfiguration_t(const std::string& prename, const std::string& source, efiEngineConfiguration_t* user);

//! Generate a string that describes the contents of a InjectorConfiguration packet
std::string textPrintefiInjectorConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiInjectorConfiguration_t
std::string textPrintefiInjectorConfiguration_t(const std::string& prename, const efiInjectorConfiguration_t* user);

//! Read the contents of a efiInjectorConfiguration_t from text
int textReadefiInjectorConfiguration_t(const std::string& prename, const std::string& source, efiInjectorConfiguration_t* user);

//! Generate a string that describes the contents of a RPMController packet
std::string textPrintefiRPMControllerPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiRPMController_t
std::string textPrintefiRPMController_t(const std::string& prename, const efiRPMController_t* user);

//! Read the contents of a efiRPMController_t from text
int textReadefiRPMController_t(const std::string& prename, const std::string& source, efiRPMController_t* user);

//! Generate a string that describes the contents of a efiMaintenanceItemConfig_t
std::string textPrintefiMaintenanceItemConfig_t(const std::string& prename, const efiMaintenanceItemConfig_t* user);

//! Read the contents of a efiMaintenanceItemConfig_t from text
int textReadefiMaintenanceItemConfig_t(const std::string& prename, const std::string& source, efiMaintenanceItemConfig_t* user);

//! Generate a string that describes the contents of a MaintenanceConfiguration packet
std::string textPrintefiMaintenanceConfigurationPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiMaintenanceConfiguration_t
std::string textPrintefiMaintenanceConfiguration_t(const std::string& prename, const efiMaintenanceConfiguration_t* user);

//! Read the contents of a efiMaintenanceConfiguration_t from text
int textReadefiMaintenanceConfiguration_t(const std::string& prename, const std::string& source, efiMaintenanceConfiguration_t* user);

//! Generate a string that describes the contents of a Table2D_1x packet
std::string textPrintefiTable2D_1xPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiTable2D_1x_t
std::string textPrintefiTable2D_1x_t(const std::string& prename, const efiTable2D_1x_t* user);

//! Read the contents of a efiTable2D_1x_t from text
int textReadefiTable2D_1x_t(const std::string& prename, const std::string& source, efiTable2D_1x_t* user);

//! Generate a string that describes the contents of a Table2D packet
std::string textPrintefiTable2DPkt(std::string prename, const efiPacket_t* pkt);

//! Generate a string that describes the contents of a efiTable2D_t
std::string textPrintefiTable2D_t(const std::string& prename, const efiTable2D_t* user);

//! Read the contents of a efiTable2D_t from text
int textReadefiTable2D_t(const std::string& prename, const std::string& source, efiTable2D_t* user);

#endif // _EFIPRINTUTIL_HPP
